---
title: "Exercise2"
output: pdf_document
date: "2023-03-21"
---

```{r Loading Libraries}
library(igraph)
library(dbplyr)
library(tidyr)
library(tidyverse)
library(tidygraph)
library(visNetwork)
```


```{r drawing the network graph}
plot_1 <- tbl_graph(nodes = nodes, edges = edges) %>%
  as.igraph() %>%
  set_vertex_attr(name = "label", value = nodes$Nodes)

# Plot with labels
plot(plot_1, vertex.label.color = "black", vertex.label.font = 2, vertex.label.dist = 0.1, layout = layout_with_fr)

plot_1_undirected<-as.undirected(plot_1)
plot_1_undirected

```

```{r Degree centrality and plot}
degree_centrality<-degree(plot_1_undirected)
degree_centrality
labels <- paste(nodes$Nodes, degree_centrality)
V(plot_1_undirected)$label <- labels

# Display graph with labels and degree centrality
plot(plot_1_undirected, vertex.size=30)

```



```{r Closeness centrality and plot}
closeness_centrality<-closeness(plot_1_undirected)
closeness_centrality
labels<-paste(nodes$Nodes, round(closeness_centrality,2))
V(plot_1_undirected)$label<-labels
plot(plot_1_undirected, vertex.size=35)

```



```{r Betweenness centrality and plot}
betweeness_centrality<-betweenness(plot_1_undirected)
betweeness_centrality
labels<-paste(nodes$Nodes, round(betweeness_centrality,3))
V(plot_1_undirected)$label<-labels
plot(plot_1_undirected,vertex.size=35)

```



```{r Final graph with all centrality}
plot_2_undirected<-as.undirected(plot_1)


degree_centrality2 <- degree(plot_2_undirected)
closeness_centrality2 <- closeness(plot_2_undirected)
betweenness_centrality2 <- betweenness(plot_2_undirected)

labels <- paste(nodes$Nodes, degree_centrality2, round(closeness_centrality2,2), round(betweenness_centrality2,2), sep = "-")

# Set vertex attribute for labels
V(plot_2_undirected)$label <- labels

# Plot graph
plot(plot_2_undirected, vertex.label.color = "black", vertex.label.font = 2, vertex.label.dist = 0.1, layout = layout_with_fr,vertex.size=40)

```

